name: update jobs

on:
  push:
    branches:
      - auto-jobs

jobs:
  update:
    name: update
    runs-on: ubuntu-latest

    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/18F/handbook/hooks | jq ".[].id"